apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: app-service-ns
data:
  SPRING_PROFILES_ACTIVE: "docker"
  JWT_EXPIRATION: "1800000"
  JWT_REFRESH_TOKEN_EXPIRATION: "86400000"
  USER_SERVICE_URL: "http://user-service:8081"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_HIBERNATE: "INFO"
  LOGGING_LEVEL_LIQUIBASE: "INFO"

