apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: app-service-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-postgres-service:5432/authdb"
  SPRING_DATASOURCE_USERNAME: "username"
  SPRING_DATASOURCE_PASSWORD: "password"
  JWT_SECRET: "secret"

  