apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: payment-service-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth_db:5432/${AUTH_DB_NAME}"
  SPRING_DATASOURCE_USERNAME: "username"
  SPRING_DATASOURCE_PASSWORD: "password"
  JWT_SECRET: "secret"

  