apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
  namespace: app-service-ns
spec:
  serviceName: user-postgres
  replicas: 1

  selector:
    matchLabels:
      app: user-postgres
  
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          
          envFrom:
            - secretRef:
              name: user-postgres-secret
          
          volumeMounts:
            - name: user-postgres-storage
              mountPath: /var/lib/postgresql/data

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - user
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - user
            initialDelaySeconds: 10
            periodSeconds: 5

  volumeClaimTemplates:
    - metadata:
        name: user-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi