apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: app-service-ns
data:
  AUTHSERVICE_URL: "http://auth-service:8082"
  USERSERVICE_URL: "http://user-service:8081"
  ORDERSERVICE_URL: "http://order-service:8080"
  PAYMENTSERVICE_URL: "http://payment-service:8084"
  AUTHSERVICE_WHITELIST: "/api/v1/auth/login,/api/v1/auth/register,/api/v1/auth/refresh,/api/v1/auth/validate"
  SPRING_PROFILES_ACTIVE: "docker"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_HIBERNATE: "INFO"
  LOGGING_LEVEL_LIQUIBASE: "INFO"
