apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: daryamashnyuk/userservice:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
              configMapKeyRef:
                name: user-config
                key: SPRING_DATASOURCE_URL
            
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: REDIS_HOST

            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: REDIS_PORT

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SPRING_PROFILES_ACTIVE
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5