apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: app-service-ns
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  SPRING_DATASOURCE_URL: "jdbc:postgresql://user-postgres-service:5432/userdb"