apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: app-service-ns
data:
  PAYMENT_CLIENT_URL: "https://www.random.org"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_PAYMENT_TOPIC_NAME: "payment-events"
  KAFKA_ORDER_TOPIC_NAME: "order-events"
  SPRING_PROFILES_ACTIVE: "docker"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_ORG_HIBERNATE: "INFO"
  LOGGING_LEVEL_LIQUIBASE: "INFO"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "payment-service-group"
  SPRING_MAIN_LAZY_INITIALIZATION: "false"