apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: daryamashnyuk/paymentservice:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8084

          envFrom:
            - configMapRef:
              name: payment-config
            - secretRef:
              name: payment-service-secret

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5