apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: app-service-ns
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: daryamashnyuk/paymentservice:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8084

          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx300M -Xms200M -XX:+UseSerialGC -Dspring.main.lazy-initialization=true"

          envFrom:
            - configMapRef:
                name: payment-config
            - secretRef:
                name: payment-service-secret

          livenessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 150
            periodSeconds: 20

          readinessProbe:
            tcpSocket:
              port: 8084
            initialDelaySeconds: 120
            periodSeconds: 10

          resources:
            requests:
              memory: "400Mi"
              cpu: "100m"
            limits:
              memory: "800Mi"