apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: app-service-ns
type: Opaque
stringData:
  MONGO_URL: "mongodb://payment-mongo:27017/payments"
  LIQUIBASE_MONGODB_URL: "mongodb://payment-mongo:27017/payments"
