apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: app-service-ns
type: Opaque
stringData:
  MONGO_URL: "mongodb://admin:secret@payment-mongo-service:27017/payments?authSource=admin"
  LIQUIBASE_MONGODB_URL: "mongodb://admin:secret@payment-mongo-service:27017/payments?authSource=admin"
