apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: order-service-ns
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-order-service:29092"
  KAFKA_PAYMENT_TOPIC_NAME: "payment-events"
  KAFKA_ORDER_TOPIC_NAME: "order-events"
  SPRING_PROFILES_ACTIVE: "docker"

