apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: daryamashnyuk/orderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080

          envFrom:
            - configMapRef:
              name: order-config
            - secretRef:
              name: order-service-secret

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5