apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: app-service-ns
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: daryamashnyuk/orderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: SPRING_LIQUIBASE_LAZY_INITIALIZATION
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx300M -Xms200M -XX:+UseSerialGC -Dspring.main.lazy-initialization=true"
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-service-secret

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 5

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "800Mi"