apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: app-service-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://order-postgres-service:5432/orderdb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
