apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://order-db:5432/orderdb"
  SPRING_DATASOURCE_USERNAME: "username"
  SPRING_DATASOURCE_PASSWORD: "password"
